name: CI

on:
  push:

env:
  APP_ENV: ci

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Start Docker
        run: |
          cp .env.example .env
          cp .docker.env.example .docker.env
          docker network create traefik
          docker-compose -f docker-compose.yaml -f .github/docker-compose.override.yaml up -d

      - name: Install dependencies
        run: make vendor

      - name: Install Drupal
        run: >
          ./bin/drush.sh
          site:install -y
          config_installer

      - name: Test loading the home page.
        run: >
          curl http://localhost:8000

      - name: Verify the home page has the site name in it.
        run: >
          curl -s http://localhost:8000 | grep "PHP South Wales"

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Start Docker
        run: |
          cp .env.example .env
          cp .docker.env.example .docker.env
          docker network create traefik
          docker-compose -f docker-compose.yaml -f .github/docker-compose.override.yaml up -d

      - name: Install dependencies
        run: make vendor

      - name: Execute tests
        run: make test-unit
        env:
          SIMPLETEST_BASE_URL: http://localhost:8000