name: CI

on:
  push:

env:
  APP_ENV: ci

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          extensions: mbstring
          coverage: none
          tools: composer:v1

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest

      - name: Install Drupal
        run: >
          vendor/bin/drush --root=$(pwd)/web
          site:install -y
          config_installer
          --db-url=sqlite://sites/defalt/files/.ht.sqlite

      - name: Start a web server
        run: php -S localhost:8000 -t web 2>&1 &

      - name: Test loading the home page.
        run: >
          curl http://localhost:8000

      - name: Verify the home page has the site name in it.
        run: >
          curl -s http://localhost:8000 | grep "PHP South Wales"

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          extensions: mbstring
          coverage: none
          tools: composer:v1

      - name: Install the Symfony local web server
        run: |
          wget https://get.symfony.com/cli/installer -O - | bash
          mv /home/runner/.symfony/bin/symfony /usr/local/bin/symfony

      - name: Install dependencies
        run: symfony composer install --prefer-dist --no-interaction --no-suggest

      - name: Start the local web server
        run: symfony serve -d

      - name: Execute tests
        run: make test
        env:
          SIMPLETEST_BASE_URL: http://localhost:8000

      - name: Stop the local web server
        run: symfony server:stop
